server:
  port: 8081
spring:
  batch:
    job:
      enabled: false
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: 'ANT_PATH_MATCHER    '
